Audit
malikhaiderkhan/Vet-Clinic pull request #5
Opened 2023-09-11 17:58 UTC by malikhaiderkhan

### Highlights

**Performance before**
![s1](https://github.com/malikhaiderkhan/Vet-Clinic/assets/48483877/46e9cb85-43f2-4610-a441-d846b8304efc)
![s2](https://github.com/malikhaiderkhan/Vet-Clinic/assets/48483877/b045e33c-8fa3-4ec7-b3a3-27d0bfc6bf32)
![s3](https://github.com/malikhaiderkhan/Vet-Clinic/assets/48483877/59431675-1f4f-4608-a488-4890b9af6e7d)

**After indexing performance**
![s4](https://github.com/malikhaiderkhan/Vet-Clinic/assets/48483877/3cb65473-14b1-40a3-ad8c-7d37ec3fbdfb)
![s5](https://github.com/malikhaiderkhan/Vet-Clinic/assets/48483877/2adbb408-4cc0-40dd-a7dc-c72d1c02e273)
![s6](https://github.com/malikhaiderkhan/Vet-Clinic/assets/48483877/ddb1a83b-b2d3-47f7-b672-d31ce7e5a924)

2023-09-11 18:32 UTC, shahadat3669 requested changes
Hi @sulaimonaa, @malikhaiderkhan 

Great job so far! 👏 You've done well, and you're almost there for the next project ⏭️, but there are a few issues 🐛 that you still need to work on.

<img  src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif" />


## Don't Worry 🙏

It's okay to have bugs in your code. 🆗 Please see this code review as an opportunity to learn practical coding skills and discover new tips that can improve your code quality 💯 and help you **get even better** 💼.

**I will guide you on how to address these areas down below 👇.**

## Highlights
✅ Included a pair of screenshots with the results of the  EXPLAIN ANALYZE.
✅ `INSERT INTO` queries are saved in the data.sql file.
✅ Add the requested extra column.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadata3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

## ⚠️ WARNING ⚠️

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-11 18:32 UTC, shahadat3669 commented on queries.sql
> +CREATE INDEX idx_email ON owners (email);
👍 Good progress on adding the indexes! However, there's a small adjustment to make to align with the curriculum guidelines.

- [ ] Currently, your index creation operation is inside the `queries.sql` file. According to the [curriculum-databases-projects-template](https://github.com/microverseinc/curriculum-template-databases#:~:text=This%20repository%20includes,Use%20them%20responsibly!), `CREATE` operations like index creation should be inside the `schema.sql` file. Kindly move these operations to the appropriate `schema.sql` file.

By organizing your SQL scripts this way, you'll ensure that your project structure aligns with the curriculum guidelines. Keep up the great work! 👍📜

2023-09-11 18:32 UTC, shahadat3669 commented on queries.sql
> +EXPLAIN ANALYZE SELECT * FROM owners where email = 'owner_18327@mail.com';
👍 Great effort in optimizing your SQL queries! Optimizing queries can be challenging, but you're on the right track. Let's delve into the details:

- [x] Your first query, concerning `animals_id`, appears to be working well. Both before and after creating the index, it returns the same number of rows (10 rows), which is a positive sign. 👍 

- [ ] However, in the second query, focusing on `vet_id`, there's a slight inconsistency. Before creating the index, it shows **5 rows**, but after indexing, it shows **6 rows**. Additionally, it seems you've applied a query limit after indexing. To gain a clearer understanding, I recommend running both queries in the same database, ensuring they operate on the same dataset, and executing them without any query limits. Please provide screenshots of the results for both scenarios.

| Before indexing | After indexing|
| --- | --- |
|  ![image](https://github.com/malikhaiderkhan/Vet-Clinic/assets/55840999/99ddc327-71fc-401d-9077-7b1ed81a71eb)| ![image](https://github.com/malikhaiderkhan/Vet-Clinic/assets/55840999/099ba8c3-9dd3-44d9-b0b5-dd74a078b6a9)|

- [ ] Regarding the third query, even though you haven't applied a query limit, there's a discrepancy in the results. Before indexing, it shows 8 rows, but after indexing, it returns 4 rows. To investigate this further, I suggest running both queries in the same database, containing an identical dataset, and sharing screenshots of the results for both queries.

| Before indexing | After indexing|
| --- | --- |
|  ![image](https://github.com/malikhaiderkhan/Vet-Clinic/assets/55840999/f335df7b-cb62-4371-a69b-b57833aa08cd)| ![image](https://github.com/malikhaiderkhan/Vet-Clinic/assets/55840999/06eedb4d-e7ae-470d-8030-45f96d5261a9) |

By performing these tests and sharing the results, we can better understand the impact of indexing on your queries. Keep up the excellent work in optimizing your database operations! 👍🔍📊

2023-09-12 05:42 UTC, nicupop729 reviewed
Hello  @team 👋,

_This is an additional review as a result of the second opinion request._

Kudos for the nice effort in this milestone!

For this project, let's only focus on the fact that for the "EXPLAIN ANALYZE SELECT * FROM visits where vet_id = 2;", the query planner output in the "After indexing performance" screenshot is not using the index (there is no Index scan in the output but you can see Seq scan and Filter - please compare this output with the other 2 outputs from the "After" to spot the difference). 
Let's please remove indexes and add them once again. Afterwards, please take screenshots of the `explain analyze` output one more time.

When that is done, please ask for another review from your dashboard.

Keep rocking 🚀!

2023-09-12 08:26 UTC, malikhaiderkhan commented
Now after the request on second opinion the reviewer asked me that index scan is not visible in screenshot. So I remove the index and after adding it again now i got the index scan on query "EXPLAIN ANALYZE SELECT * FROM visits where vet_id = 2;" and also the execution time drops by adding indexing. The updated screenshots are also attached above.

2023-09-12 08:34 UTC, V-Blaze approved these changes
Hi @malikhaiderkhan, @sulaimonaa  

# Approved 🟢 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy](https://user-images.githubusercontent.com/107632780/229644741-7dea3027-bf3f-4416-855b-46095e3bf6d5.gif)

## Highlights

- Used `indexes` to decrease execution time 💯
-  Screenshot shows before and after improvemnts👍
-  Nice communication with reviewer 🟢 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-12 08:36 UTC, merged